baseURL                = "https://demo.stack.cai.im/"
locale                 = "en-us"
title                  = "路西残卷"
# Theme i18n support
# See i18n folder for available languages
defaultContentLanguage = "en"
# Set hasCJKLanguage to true if DefaultContentLanguage is a CJK language
# This will make .Summary and .WordCount behave correctly
hasCJKLanguage         = false
theme                  = "hugo-theme-stack"

