baseURL                = "https://SunHaohao-Jou.github.io/"
title                  = "路西残卷"
defaultContentLanguage = "zh"
hasCJKLanguage         = true
theme                  = "hugo-theme-stack"

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"
